# Generated by Django 5.2.2 on 2025-06-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('june6app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='sign',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
