# Generated by Django 5.2.2 on 2025-06-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('june6app', '0002_contact_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='hear',
            field=models.TextField(max_length=122, null=True),
        ),
    ]
