# Generated by Django 5.2 on 2025-08-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('june6app', '0004_alter_contact_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='sign',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
